# Generated by Django 2.2.3 on 2019-07-04 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_productname_capitalize'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productimage',
            old_name='thumbnails',
            new_name='thumbnail',
        ),
    ]
